config/routes.rb
Rails.application.routes.draw do

  resources :reports
  resources :appointment, :controller=>:appointments
  devise_for :staff

  root to: 'home#index'

  get '/settings', to: 'settings#index'
  put '/settings', to: 'settings#update'

  put '/appointment/:id/finalize', to: 'appointments#finalize_appointment', as: 'finalize_appointment', controller: 'AppointmentsController'

  resources :staff

  post '/staff/:id/edit', to: 'staff#edit'
  post '/staff/save_perfil', to: 'staff#staff_save_perfil', as: 'modify_perfil'

  scope :branch_offices do
    put ':id/attention_types', to: 'branch_offices#update_attention_types_estimations'
  end

  scope :staff do
    put ':id/time_blocks', to: 'staff#update_time_blocks'
  end

  get '/staff/appointments/reassing', to: 'staff#new_reassign_appointments_to_executive'
  post '/staff/appointments/reassing', to: 'staff#reassign_appointments_to_executive'

  get '/staff/editar/select', to: 'staff#select'
  post '/staff/editar/select', to: 'staff#select'

  get '/staff/show/appointments/until/:days', to: 'staff#show_appointments', as: 'staff_show_appointments'


  scope :api do

    # Servicio que entrega un JSON con regiones, y en cada region, sus comunas,
    # y anidadas sus sucursales. Sirve para poder buscar una sucursal por lugar.
    get '/regions/comunas/branch_offices', to: 'branch_offices#get_by_location'

    # Necesita parametros --> latitude , longitude
    get '/branch_offices/nearest', to: 'branch_offices#nearest'

    get '/attention_types', to: 'attention_types#index'

    # Servicio que entrega las horas en donde se puede efectuar una reunion.
    # Los parametros son la sucursal (ID), tipo de atencion (ID), y el dia.
    get '/appointments/:yyyy/:mm/:dd/branch_office/:branch_office_id/attention_type/:attention_type_id',
    to: 'appointments#get_available_times'

    post '/appointments/schedule_appointment', to: 'appointments#schedule_appointment'

    post '/appointments/reschedule_appointment', to: 'appointments#reschedule_appointment'

    post '/appointments/confirm_appointment', to: 'appointments#confirm_appointment'

    get '/appointments/current', to: 'appointments#current_appointment'

    delete '/appointments/cancel', to: 'appointments#cancel_appointment'

  end

end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  auto_strip_attributes :names, :squish => true
  auto_strip_attributes :first_surname, :squish => true
  auto_strip_attributes :second_surname, :squish => true

  has_many :staff_took_appointment, :class_name => "Appointment", :foreign_key => "staff_took_appointment_id"

  validates_length_of :names, :minimum => 1
  validates_length_of :first_surname, :minimum => 1
  validates_presence_of :type

  after_validation :capitalize_name

  def full_name
    full = names + ' ' + first_surname
    if second_surname
      full = full + ' ' + second_surname
    end
    return full
  end

  def name_surname
    names.split(" ")[0] + " " + first_surname
  end

  def executive?
    self.is_a? Executive
  end

  def supervisor?
    self.is_a? Supervisor
  end

  def manager?
    self.is_a? Manager
  end

  def admin?
    self.is_a? Admin
  end

  private
  def capitalize_name
    return unless errors.blank?
    self.names = self.names.split.map(&:capitalize)*' '
    self.first_surname = self.first_surname.split.map(&:capitalize)*' '
    self.second_surname = self.second_surname.split.map(&:capitalize)*' ' if self.second_surname
  end


end

app/controllers/staff_controller.rb
class StaffController < ApplicationController

  before_action :authenticate_staff!
  before_action :set_staff, only: [:update_time_blocks]

  def pundit_user
    current_staff
  end


  def new
    authorize Staff

    if current_staff.manager?
      @branch_office = current_staff.branch_office.full_address
    end

  end

  def create

    attributes = staff_params
    attributes[:password] = params[:staff][:password]
    attributes[:password_confirmation] = params[:staff][:password_confirmation]

    # Para que la ID de la sucursal sea la misma que el jefe de sucursal que esta creando el usuario
    if current_staff.manager?
      attributes[:branch_office_id] = current_staff.branch_office_id
    end

    newStaff = Staff.new(attributes)

    unless StaffPolicy.new(current_staff, newStaff).create?
      raise Pundit::NotAuthorizedError
    end

    if newStaff.save
      render json: newStaff, status: :created
    else
      render json: newStaff.errors, status: :unprocessable_entity
    end
  end


  def update_time_blocks

    unless StaffPolicy.new(current_staff, @staff).update_time_blocks?
      raise Pundit::NotAuthorizedError
    end


    time_blocks = params[:time_blocks]

    ActiveRecord::Base.transaction do
      TimeBlock.where(executive_id: @staff.id).delete_all
      time_blocks.each do |block|
        @staff.time_blocks << TimeBlock.new(
          :weekday => block[:weekday],
          :hour => block[:hour],
          :minutes => block[:minutes])
      end
    end

    render :json => {}, :status => :ok
  end

  def staff_save_perfil
    was_saved = true
    if params[:assignment_show_until_days]
      current_staff.assignment_show_until_days = params[:assignment_show_until_days].to_i
      was_saved = was_saved && current_staff.save
    end

    if was_saved
      flash[:notice] = "Perfil saved"
      redirect_to "/staff/#{current_staff.id}"
    else
      flash[:notice] = "Perfil not saved"
      redirect_to "/staff/#{current_staff.id}"
    end
  end

  def show_appointments
    if !current_staff.executive?
      raise Pundit::NotAuthorizedError
    end

    @appointments = current_staff.appointments.where(:time => DateTime.current.beginning_of_day..DateTime.current.end_of_day.advance(:days => params[:days].to_i))

  end

  def new_reassign_appointments_to_executive
    if current_staff.executive?
      raise Pundit::NotAuthorizedError
    end

    # Encontrar ejecutios de la misma sucursal

    if(current_staff.supervisor?)
      @ejecutivos = Executive.all.where(:branch_office => current_staff.branch_office_id,:attention_type => current_staff.attention_type_id)
    else
      @ejecutivos = Executive.all.where(:branch_office => current_staff.branch_office_id)
    end

  end

  def reassign_appointments_to_executive
    if current_staff.executive?
      raise Pundit::NotAuthorizedError
    end

    executive_to_take_appointments_out = Executive.find(params[:executives_appointment_taked_away].to_i)
    executive_to_put_appointments_in = Executive.find(params[:executives_appointment_putted_in].to_i)

    if executive_to_take_appointments_out.reassign_appointments_to(executive_to_put_appointments_in)
      flash[:notice] = "Appointments successfully assigned"
      redirect_to "/staff/appointments/reassing"
    else
      flash[:notice] = "Appointments wasn't assigned"
      redirect_to "/staff/appointments/reassing"
    end

  end

  def show

  end

  def edit
    @staff = Staff.find(params[:id])
  end

  def select
    @staffs = Staff.all
  end

  def update
    staff = Staff.find(params[:id])
    nombre = params[:nombre]
    papellido = params[:first_surname]
    sapellido = params[:second_surname]
    email = params[:email]
    staff.update(names: nombre)
    staff.update(first_surname: papellido)
    staff.update(second_surname: sapellido)
    staff.update(email: email)
    redirect_to action: "select"
  end

  private
  def set_staff
    @staff = Staff.find(params[:id])
  end

  def staff_params
    params.fetch(:staff).permit(:names, :first_surname, :second_surname, :branch_office_id, :type, :email)
  end

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController

  before_action :authenticate_staff!
  #before_action :set_staff, only: [:update, :destroy]

  def pundit_user
    current_staff
  end

  def new
    authorize Staff
  end

  def create
    staff = Staff.new(staff_params)
    authorize @staff

    if staff.save
      render json: staff, status: :created
    else
      render json: staff.errors, status: :unprocessable_entity
    end
  end


  private
  def set_staff
    @staff = Staff.find(params[:id])
  end

  def staff_params
    params.fetch(:staff).permit(:names, :first_name, :second_name, :branch_office, :position)
  end

end

app/views/staff/_form.html.erb
<%= form_for :staff do |f| %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :names %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :apellido_paterno %>
    <%= f.text_field :first_surname %>
  </div>  

  <div class="field">
    <%= f.label :apellido_materno %>
    <%= f.text_field :second_surname %>
  </div>  

</div>
  <div class="actions">
    <%= f.submit "Actualizar usuario" %>
  </div>
<% end %>

app/views/staff/edit.html.erb
<h2> Editar usuario </h2>

<%= form_for @staff, :url => {:action => "update"}  do |f| %>

  <div class="field">
    <%= f.label :nombre  %>
    <%= f.text_field :names, :name => "nombre" %>
  </div>
  <div class="field">
    <%= f.label :contraseña %>
    <input type="password" placeholder="<NUEVA CONTRASEÑA>" %>
  </div>
  <div class="field">
    <%= f.label :apellido_paterno %>
    <%= f.text_field :first_surname, :name => "first_surname" %>
  </div>  

  <div class="field">
    <%= f.label :apellido_materno %>
    <%= f.text_field :second_surname, :name => "second_surname" %>
  </div>   
  <div class="actions">
    <%= f.submit "Actualizar usuario" %>
  </div>
<% end %>

app/views/staff/new.html.erb
<form id="new-user-form" class="row">

  <div class="col-md-12">
    <h2>Crear personal</h2>
  </div>

  <div class="col-md-6">
    <div class="row">
      <div class="col-md-12">

        <div class="content-box-large box-with-header">

          <div class="form-group" title="Todos los nombres de la persona (sin incluir apellidos)" rel="tooltip">
            <label for="names" class="col-2 col-form-label">Nombres</label>
            <div class="col-10">
              <input class="form-control" type="text" name="names" id="names" placeholder="Juan Pedro">
            </div>
          </div>

          <div class="form-group">
            <label for="first-surname" class="col-2 col-form-label">Primer apellido</label>
            <div class="col-10">
              <input class="form-control" type="text" name="first-surname" id="first-surname" placeholder="Apellido paterno">
            </div>
          </div>

          <div class="form-group">
            <label for="second-surname" class="col-2 col-form-label">Segundo apellido</label>
            <div class="col-10">
              <input class="form-control" type="text" name="second-surname" id="second-surname" placeholder="Apellido materno (campo opcional)">
            </div>
          </div>

          <div class="form-group">
            <label for="email" class="col-2 col-form-label">E-mail</label>
            <div class="col-10">
              <input class="form-control" type="email" name="email" id="email" placeholder="Correo del usuario">
            </div>
          </div>

          <div class="form-group">
            <label for="password" class="col-2 col-form-label">Contraseña</label>
            <div class="col-10">
              <input class="form-control" type="password" name="password" id="password" placeholder="Contraseña del usuario">
            </div>
          </div>

          <div class="form-group">
            <label for="password-confirmation" class="col-2 col-form-label">Confirmar contraseña</label>
            <div class="col-10">
              <input class="form-control" type="password" name="password-confirmation" id="password-confirmation" placeholder="Confirmar contraseña del usuario">
            </div>
          </div>

          <div class="form-group">
            <label class="col-2 col-form-label">Tipo de personal</label>
            <select class="form-control" name="type" id="type">

              <option value="Executive">Ejecutivo</option>
              <option value="Supervisor">Supervisor</option>

              <% if current_staff.admin? %>
                <option value="Manager">Jefe de sucursal</option>
                <option value="Admin">Administrador</option>
              <% end %>
            </select>
          </div>



          <% if current_staff.admin? %>
            <div class="form-group" id="branch-office-list-by-location">
              <label class="col-2 col-form-label">Seleccione sucursal</label>

              <div id="office-selector">

              </div>
            </div>
          <% else %>
            <p>
              El nuevo usuario sera asignado a la sucursal <b><%= @branch_office %></b>
            </p>
          <% end %>




        </div>
      </div>
    </div>
  </div>

  <div class="col-md-12">
    <button type="submit" class="btn btn-primary" id="save-user">Crear usuario</button> <span style="display: none;" class="glyphicon glyphicon-refresh spinning"></span>
  </div>

</form>

app/views/staff/new_reassign_appointments_to_executive.html.erb
<form id="reassign-appointment-to-executive-form" class="row" action="<%=staff_appointments_reassing_path%>" method="post">
  <input type="hidden"
       value="<%= form_authenticity_token() %>"
       name="authenticity_token"/>
  <div class="col-md-12">
    <h2>Reasignar horas de ejecutivos</h2>
  </div>

  <div class="col-md-6">
    <div class="row">
      <div class="col-md-12">

        <div class="content-box-large box-with-header">

          <div class="form-group" title="Seleccione al ejecutivo al que se le reemplazará su carga horaria" rel="tooltip">
            <label for="names" class="col-2 col-form-label">Quitar asignaciones de horas a</label>
            <div class="col-10">
              <select class="form-control" name="executives_appointment_taked_away" id="names_out">
                <option value="" disabled selected>Seleccione un ejecutivo</option>
                <%= options_from_collection_for_select(@ejecutivos, :id, :full_name) %>
              </select>
            </div>
          </div>

          <div class="form-group" title="Seleccione al ejecutivo al que se le agregará la carga horaria" rel="tooltip">
            <label for="names" class="col-2 col-form-label">Agregar asignaciones de horas a</label>
            <div class="col-10">
              <select class="form-control" name="executives_appointment_putted_in" id="names_in">
                <option value="" disabled selected>Seleccione un ejecutivo</option>
                <%= options_from_collection_for_select(@ejecutivos, :id, :full_name, @ejecutivo_seleccionado) %>
              </select>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>

  <div class="col-md-12">
    <button type="submit" class="btn btn-primary" id="save-assignment">Reasignar carga horaria</button> <span style="display: none;" class="glyphicon glyphicon-refresh spinning"></span>
  </div>

</form>

app/views/staff/select.html.erb
<h2> Edición de usuario </h2>

<table class="table"> 
<thead>
	<tr>
		<th>Nombre</th>
		<th>Email</th>
		<th>Apellido Paterno </th>
		<th>Apellido Materno </th>
		<th colspan="1"></th>
	</tr>
</thead>
<tbody>
	<%@staffs.each do |staff| %>
		<tr>
			<td><%= staff.names %></td>
			<td><%= staff.email %></td>
			<td><%= staff.first_surname %></td>
			<td><%= staff.second_surname %></td>
			<td><%= link_to 'Editar', edit_staff_path(staff)%></td>
		</tr>
	<% end %>
</tbody>
</table>

app/views/staff/show.html.erb
<form id="perfil_form" class="row" action="<%=modify_perfil_path%>" method="post">
  <h2> Perfil </h2>
  <input type="hidden"
       value="<%= form_authenticity_token() %>"
       name="authenticity_token"/>
  <div>
    <tr>
  		<td>Cambiar las citas que se pueden ver a: </td>
      <td> <input name="assignment_show_until_days" type="number" min="1" value="<%= current_staff.assignment_show_until_days %>"> </input> </td>
      <td> dias</td>
    </tr>
  </div>
  <div class="col-md-12">
    <button type="submit" class="btn btn-primary" id="save-perfil">Guardar</button> <span style="display: none;" class="glyphicon glyphicon-refresh spinning"></span>
  </div>
</form>

app/views/staff/show_appointments.html.erb
<h2> Citas </h2>


<table class="table">
<thead>
	<tr>
		<th>Hora agendada</th>
		<th>Cliente</th>
		<th>Propietario de la hora </th>
		<th>Tipologia </th>
    <th>Estado </th>
		<th colspan="1"></th>
	</tr>
</thead>
<tbody>
	<%@appointments.each do |appoint| %>
		<tr>
			<td><%= appoint.time %></td>
			<td><%= appoint.client_names %></td>
			<td><%= appoint.staff_owner_appointment.full_name %></td>
			<td><%= appoint.staff_owner_appointment.attention_type.name %></td>
      <td><%= appoint.status %></td>
			<td><%= link_to 'Ver', appointment_path(appoint)%></td>
		</tr>
	<% end %>
</tbody>
</table>