config/routes.rb
Rails.application.routes.draw do

  resources :reports
  resources :appointment, :controller=>:appointments
  devise_for :staff

  root to: 'home#index'

  get '/settings', to: 'settings#index'
  put '/settings', to: 'settings#update'

  put '/appointment/:id/finalize', to: 'appointments#finalize_appointment', as: 'finalize_appointment', controller: 'AppointmentsController'

  resources :staff

  post '/staff/:id/edit', to: 'staff#edit'
  post '/staff/save_perfil', to: 'staff#staff_save_perfil', as: 'modify_perfil'

  scope :branch_offices do
    put ':id/attention_types', to: 'branch_offices#update_attention_types_estimations'
  end

  scope :staff do
    put ':id/time_blocks', to: 'staff#update_time_blocks'
  end

  get '/staff/appointments/reassing', to: 'staff#new_reassign_appointments_to_executive'
  post '/staff/appointments/reassing', to: 'staff#reassign_appointments_to_executive'

  get '/staff/editar/select', to: 'staff#select'
  post '/staff/editar/select', to: 'staff#select'

  get '/staff/show/appointments/until/:days', to: 'staff#show_appointments', as: 'staff_show_appointments'


  scope :api do

    # Servicio que entrega un JSON con regiones, y en cada region, sus comunas,
    # y anidadas sus sucursales. Sirve para poder buscar una sucursal por lugar.
    get '/regions/comunas/branch_offices', to: 'branch_offices#get_by_location'

    # Necesita parametros --> latitude , longitude
    get '/branch_offices/nearest', to: 'branch_offices#nearest'

    get '/attention_types', to: 'attention_types#index'

    # Servicio que entrega las horas en donde se puede efectuar una reunion.
    # Los parametros son la sucursal (ID), tipo de atencion (ID), y el dia.
    get '/appointments/:yyyy/:mm/:dd/branch_office/:branch_office_id/attention_type/:attention_type_id',
    to: 'appointments#get_available_times'

    post '/appointments/schedule_appointment', to: 'appointments#schedule_appointment'

    post '/appointments/reschedule_appointment', to: 'appointments#reschedule_appointment'

    post '/appointments/confirm_appointment', to: 'appointments#confirm_appointment'

    get '/appointments/current', to: 'appointments#current_appointment'

    delete '/appointments/cancel', to: 'appointments#cancel_appointment'

  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Setting['look-feel.title'] %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
	     <div class="container">
	        <div class="row">
	           <div class="col-md-5">
	              <!-- Logo -->
	              <div class="logo">
	                 <h1><a href="index.html"><%= image_tag("logo35x26.png") %> <%= Setting['look-feel.header'] %></a></h1>
	              </div>
	           </div>
	           <div class="col-md-5">
	              <div class="row">
	                <div class="col-lg-12">
	                  <div class="input-group form">
	                       <input type="text" class="form-control" placeholder="Search...">
	                       <span class="input-group-btn">
	                         <button class="btn btn-primary" type="button">Search</button>
	                       </span>
	                  </div>
	                </div>
	              </div>
	           </div>
             <% if current_staff %>
	           <div class="col-md-2">
	              <div class="navbar navbar-inverse" role="banner">
	                  <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
	                    <ul class="nav navbar-nav">
	                      <li class="dropdown">
	                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_staff.name_surname %> <b class="caret"></b></a>
	                        <ul class="dropdown-menu animated fadeInUp">
	                          <li><a href="profile.html">Cuenta</a></li>
	                          <li><%= link_to 'Cerrar sesión', :destroy_staff_session %></li>
	                        </ul>
	                      </li>
	                    </ul>
	                  </nav>
	              </div>
	           </div>
             <% end %>
	        </div>
	     </div>
	</div>

    <div class="page-content">
      <div class="row">

        <div class="col-md-2">

          <% if current_staff %>
          <div class="sidebar content-box" style="display: block;">
                  <ul class="nav">


                    <% if current_staff.admin? || current_staff.manager? %>
                    <li><a href="<%= new_staff_path %>"><i class="glyphicon glyphicon-user"></i> Crear usuario</a></li>
                    <% end %>

                    <% if current_staff.admin? || current_staff.manager? %>
                    <li><a href=/staff/editar/select><i class="glyphicon glyphicon-user"></i> Editar usuario</a></li>
                    <% end %>


                    <% if current_staff.admin? || current_staff.manager? || current_staff.supervisor?%>
                    <li><a href="<%= staff_appointments_reassing_path %>"><i class="glyphicon glyphicon-user"></i> Reasignar citas de ejecutivo</a></li>
                    <% end %>

                    <% if current_staff.executive?%>
                    <li><a href="<%= staff_show_appointments_path(current_staff.assignment_show_until_days) %>"><i class="glyphicon glyphicon-user"></i> ver citas</a></li>
                    <% end %>

                    <% if current_staff.admin? || current_staff.manager? || current_staff.supervisor?%>
                    <li><a href="<%= reports_path %>"><i class="glyphicon glyphicon-list-alt"></i> Generar reportes</a></li>
                    <% end %>

                    <% if current_staff.admin? %>
                    <li><a href="<%= settings_path %>"><i class="glyphicon glyphicon-cog"></i> Configuración global</a></li>

                    <% end %>

                    <li class="submenu">
                       <a href="#">
                          <i class="glyphicon glyphicon-list"></i> Mi cuenta
                          <span class="caret pull-right"></span>
                       </a>
                       <!-- Sub menu -->
                       <ul>
                         <li><a href="<%= staff_path(current_staff) %>">Cuenta</a></li>
                         <li><%= link_to 'Cerrar sesión', :destroy_staff_session %></li>
                      </ul>
                  </li>
              </ul>
           </div>
           <% end %>
         </div>

             <div class="col-md-10">
             <%= yield %>
             </div>

      </div>
    </div>

    <footer>
         <div class="container">

            <div class="copy text-center">
               Administración de sucursales Movistar
            </div>

         </div>
      </footer>



      <script>
          (function(){
            <% flash.each do |key, value| %>
              <%# Generar todos las notificaciones que hayan. %>
              <%# Solo escapo las 'comas simples'. %>
              <%= "$.notify('#{value.gsub("'", %q(\\\'))}', '#{key.gsub("'", %q(\\\'))}');".html_safe %>
            <% end %>
          })();
        </script>


  </body>
</html>